services:
  # Node.js service (use with: docker compose up nextjs-standalone --build)
  cal-web:
    build:
      context: cal-web/.
      dockerfile: Dockerfile
      args:
        USER_ONE_ID: "1"
        USER_ONE_NAME: "Jennifer"
        USER_TWO_ID: "2"
        USER_TWO_NAME: "Jeff"
    image: cal-web-image 
    container_name: cal-web-container
    environment:
      NODE_ENV: production
      PORT: "3000"
      USER_ONE_ID: "1"
      USER_ONE_NAME: "Jennifer"
      USER_TWO_ID: "2"
      USER_TWO_NAME: "Jeff"
      API_URL: "http://cal-api:8080"
    ports:
      - "3000:3000"
    restart: unless-stopped

  cal-api-init:
    build:
      context: cal-api/.
      target: initializer
    volumes:
      - "cal-api-assets:/data" 
    restart: "no"

  cal-api:
    build: 
      context: cal-api/.
      target: app
    image: cal-api-image
    container_name: cal-api-container
    ports:
      - "8080:8080"
    volumes:
      - "cal-api-assets:/data" 
    depends_on:
      cal-api-init:
        condition: service_completed_successfully

volumes:
  cal-api-assets:
