services:
  # Node.js service (use with: docker compose up nextjs-standalone --build)
  cal-web:
    build:
      context: cal-web/.
      dockerfile: Dockerfile
      args:
        USER_ONE_ID: "1"
        USER_ONE_NAME: "Jennifer"
        USER_TWO_ID: "2"
        USER_TWO_NAME: "Jeff"
    image: cal-web-image 
    container_name: cal-web-container
    environment:
      NODE_ENV: production
      PORT: "3000"
      USER_ONE_ID: "1"
      USER_ONE_NAME: "Jennifer"
      USER_TWO_ID: "2"
      USER_TWO_NAME: "Jeff"
      API_URL: "http://cal-api:8080"
    ports:
      - "3000:3000"
    restart: unless-stopped

  cal-api:
    build: cal-api/.
    image: cal-api-image
    container_name: cal-api-container
    ports:
      - "8080:8080"
    volumes:
      - "~/projects/home-share/cal-api/assets:/app/assets" 
