services:
  # Node.js service (use with: docker compose up nextjs-standalone --build)
  cal-web:
    build:
      context: cal-web/.
      dockerfile: Dockerfile
    image: cal-web-image 
    container_name: cal-web-container
    environment:
      NODE_ENV: production
      PORT: "3000"
      API_URL: "http://cal-api:8080"
    env_file:
      - cal-web/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

  cal-api-init:
    build:
      context: cal-api/.
      target: initializer
    volumes:
      - "cal-api-assets:/data" 
    restart: "no"

  cal-api:
    build: 
      context: cal-api/.
      target: app
    image: cal-api-image
    container_name: cal-api-container
    env_file:
      - cal-api/.env
      - cal-api/.env.production
    ports:
      - "8080:8080"
    volumes:
      - "cal-api-assets:/data" 
    depends_on:
      cal-api-init:
        condition: service_completed_successfully

volumes:
  cal-api-assets:
