CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS entries (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
	value INTEGER NOT NULL DEFAULT 0 CHECK(value IN(0, 1, 2, 3)),
	start DATETIME,
	end DATETIME,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS otps (
	email TEXT PRIMARY KEY,
	code TEXT NOT NULL,
	expires_at DATETIME
);

CREATE TABLE IF NOT EXISTS homes (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	slug TEXT NOT NULL UNIQUE,
	description TEXT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS homemates (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	home_id INTEGER REFERENCES homes(id) ON DELETE CASCADE,
	mate_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
	role INTEGER NOT NULL DEFAULT 0 CHECK(role IN(0, 1)),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

