CREATE TABLE IF NOT EXISTS lists (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	slug TEXT NOT NULL UNIQUE,
	home_id INTEGER REFERENCES homes(id) ON DELETE CASCADE,
	mate_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS listItems (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	list_id INTEGER REFERENCES lists(id) ON DELETE CASCADE,
	mate_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
	short_text TEXT,
	long_text TEXT,
	completed_at DATETIME,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
